# Generated by Django 5.0 on 2024-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earliest_pickup_date', models.DateField()),
                ('latest_pickup_date', models.DateField()),
                ('earliest_delivery_date', models.DateField()),
                ('latest_delivery_date', models.DateField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shipment_photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
