# Generated by Django 5.0.6 on 2024-06-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_shipment_delete_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='total_weight',
        ),
    ]
